# Generated by Django 4.2.23 on 2025-09-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='T001IdAutor', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('biografia', models.TextField(db_column='T001Biografia')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001Autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(db_column='T002IdEditorial', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T002Nombre', max_length=200)),
                ('direccion', models.CharField(db_column='T002Direccion', max_length=50)),
                ('telefono', models.CharField(db_column='T002Telefono', max_length=15)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T002Editorial',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='T003IdLibro', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T003Titulo', max_length=200)),
                ('resumen', models.TextField(db_column='T003Resumen')),
                ('isbn', models.CharField(db_column='T003ISBN', max_length=15)),
                ('autor', models.ForeignKey(db_column='T001IdAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='api_app.autor')),
                ('editorial', models.ForeignKey(db_column='T002IdEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T003Libro',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='T004IdMiembro', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T004Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T004Apellido', max_length=100)),
                ('email', models.EmailField(db_column='T004Email', max_length=254, unique=True)),
                ('fecha_de_membresia', models.DateField(db_column='T004FechaDeMembresia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T004Miembro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='T005IdPrestamo', editable=False, primary_key=True, serialize=False)),
                ('fecha_del_prestamo', models.DateField(db_column='T005FechaDelPestamo')),
                ('fecha_de_devolucion', models.DateField(blank=True, db_column='T005FechaDeDevolucion', null=True)),
                ('libro', models.ForeignKey(db_column='T003IdLibro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='api_app.libro')),
                ('miembro', models.ForeignKey(db_column='T004IdMiembro', on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to='api_app.miembro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'T005Prestamo',
            },
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
